services:
  - type: web
    name: truesign-app
    env: python
    buildCommand: bash build.sh
    startCommand: python app/run.py
    plan: starter
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: 1
